import type { Metadata } from "next";
import { Montserrat, Roboto, Roboto_Condensed } from "next/font/google";
import NavBar from "../components/NavBar";
import "./globals.css";
import Footer from "../components/Footer";

const montserrat = Montserrat({
    variable: "--Montserrat",
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700"]
});

const roboto = Roboto({
    variable: "--Roboto",
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700"]
});

const robotoCondensed = Roboto_Condensed({
    variable: "--Roboto_Condensed",
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700"]
});

export const metadata: Metadata = {
    title: "VitalPro App",
    description: "Generated by next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="es">
            <head>
                <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght@200;300;400;500;600;700;800" rel="stylesheet" />
            </head>
            <body className={`${montserrat.variable} ${robotoCondensed.variable} ${roboto.variable} w-full`}>
                <section className=" py-12 px-10 md:px-16 ">
                    <NavBar />
                    {children}
                </section>
                <Footer />
            </body>
        </html>
    );
}
